# Generated by Django 4.2.2 on 2024-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('yolo', models.JSONField()),
                ('yolo_version', models.CharField(max_length=255)),
                ('yolo_config', models.CharField(max_length=255)),
                ('yolo_weights', models.CharField(max_length=255)),
                ('yolo_names', models.CharField(max_length=255)),
                ('yolo_confidence', models.FloatField()),
                ('yolo_nms', models.FloatField()),
                ('yolo_size', models.IntegerField()),
                ('yolo_iou', models.FloatField()),
                ('yolo_device', models.CharField(max_length=255)),
            ],
        ),
    ]
