# Generated by Django 4.2.2 on 2024-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0002_labelledimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelledimage',
            name='labelled_image',
            field=models.ImageField(default='a', upload_to='images/'),
            preserve_default=False,
        ),
    ]
