# Generated by Django 4.2.2 on 2024-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0003_labelledimage_labelled_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelledimage',
            name='labelled_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
