# Generated by Django 4.2.2 on 2024-04-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0005_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='yolo',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_confidence',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_config',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_device',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_iou',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_names',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_nms',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_version',
        ),
        migrations.RemoveField(
            model_name='image',
            name='yolo_weights',
        ),
    ]
