# Generated by Django 4.2.2 on 2024-04-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0011_imagecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
