# Generated by Django 4.2.2 on 2024-04-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0012_image_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.CharField(default='draft', max_length=255),
        ),
    ]
