# Generated by Django 4.2.2 on 2024-04-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0014_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelledimage',
            name='h',
        ),
        migrations.RemoveField(
            model_name='labelledimage',
            name='w',
        ),
        migrations.RemoveField(
            model_name='labelledimage',
            name='x',
        ),
        migrations.RemoveField(
            model_name='labelledimage',
            name='y',
        ),
        migrations.AddField(
            model_name='labelledimage',
            name='isSegmented',
            field=models.BooleanField(default=False),
        ),
    ]
