# Generated by Django 4.2.2 on 2024-04-10 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(choices=[('image.uploaded', 'Image Uploaded'), ('image.labelled.success', 'Image Labelled Successfully'), ('image.comment', 'Image Commented'), ('image.analytics', 'Image Analytics'), ('image.delete', 'Image Deleted'), ('image.labelled.failed', 'Failed to Label Image')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
