# Generated by Django 4.2.2 on 2024-04-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_log_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('OPTIONS', 'OPTIONS')], max_length=255, null=True),
        ),
    ]
