import DashboardLayout from "@/components/Layout/DashboardLayout"
import type { Metadata } from "next"
import { cookies } from "next/headers"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const token = cookies().get("token")
    if (!token) {
        redirect("/user/login")
    }
    return <DashboardLayout>{children}</DashboardLayout>
}
